name: Build DDDASC

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    continue-on-error: false
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build web
        run: |
          cd web
          npm i --prefer-offline --no-audit
          npm run-script build
        shell: bash

      - name: Generate assets FS
        run: |
          go run -tags=dev -ldflags="-X 'github.com/var512/ddda-save-corrupter/internal/assets.WebDir=web/build'" ./tools/assets/generate.go
        shell: bash

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
