name: Tests

on:
  push:

  pull_request:

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v -tags=dev ./cmd/ddda-save-corrupter

    - name: Test
      run: go test -v -tags=dev -race ./...
